services:
  front:
    build:
      context: front
      additional_contexts:
        prince-duals-core: service:core
    ports:
      - "3366:3366"

  back:
    build:
      context: back
      additional_contexts:
        prince-duals-core: service:core
    ports:
      - "3377:3000"

  core:
    build:
      context: core
      tags:
        - "prince-duals-core"

  coverage:
    build:
      context: coverage
      additional_contexts:
        prince-duals-core: service:core
    ports:
      - 3388:80